"""document file ext

Revision ID: 2ca6a85745cf
Revises: 4e8ec93fb89e
Create Date: 2026-01-19 16:58:49.704550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ca6a85745cf'
down_revision: Union[str, None] = '4e8ec93fb89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_extension', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_extension')
    # ### end Alembic commands ###
