"""document schema

Revision ID: 4e8ec93fb89e
Revises: edd55bd41f36
Create Date: 2026-01-19 10:51:20.825814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8ec93fb89e'
down_revision: Union[str, None] = 'edd55bd41f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.Enum('REPORT', 'USER_UPLOAD', name='documenttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
